travis:
  secure:
    BINSTAR_TOKEN: ybn+6bAX40kb2+tjwu1R18wxX3w2SSB8jY07R5gq47Nn3M+BasSLs3DxoHC3kwzFHLtK6/oRMnwbPLeE0t8BqWdXst3Qb+2rKsqHiK8Qdq7dKETaIR2VjtcCQzrdbwIhrV8Pnz2DbpM3MMA776/L7GrmnJZ5HqeDvJzUhbk+VwKMs1gMNHFjmtS5sbiRSQF5ujV67KqFlCA+HZ9ncNiIkCbHtfllxKQ1ToLYqwyegooOPW6+XuO5QHwPwgMpRAbWZPkCusizuKO1eC/7A5KTRWPlFTo0krUC8eaHYzy4ZIKVjKNBcD9XPlOjMowolaC/LSX8mJdLLal/b7SvDDAfERK+7yAMtoVk3LHOgIbyrUfnfpB+a/GTyj4OKMJuJB3YsGFufpU3tSzAZo54+ueyvUOBajfcu7IsbQtkx6ika7h/724FlckVPhUen2jRPg5sHbIKZMmbvWNXTRs61a+MtFVBJfc5XLbcuSIv9eRMM4zmeza07MEzhGqyf5rXjLVx2Gl4Gm0Ppa25RkRmAdlBWwq+uPTWRq1NtTaUSgBxHGViqM/pZQxz1lpuVu8xg6Tgp8JEzhi3opt6FaQtOP1N6Z3jEhJLYZmNCpCb4JrjEb6lM/ZPoSPH00zWNSF2Eppku1Kiq4LyGU4HioPzLmGOANfukERbb9516nnuSoSKSgQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
